### ISSUE TITLE
Design of Actions for State Machine

### ISSUE THREAD

**Issue by jaivgar** [jaivgar/StateMachine-engine#1]
The Actions of a State Machine are not well defined yet (See 6fb0253c3f41c27942d32504168778c29a2634bc).
They need to support a lot of flexibility, as is probably the part that will be customized the most when used. Some actions will print things on the screen, others could modify the environment of the State Machine, or raise an Event, or even send a Service request, etc.

The first design idea was to have a basic parent class, and every new Action could extend it, to create a personalized class and override its trigger method.

The second idea was to have a class that implements a functional interface and takes as argument a method. Then the only requirements when using this option is to pass the lambda function when creating the Action object.

Which would be better/easier to use, for creating new systems? @emanuelpalm

**Comment by emanuelpalm** [comment]
Both designs are very adequate. I would probably go with the second, but only because it fits my personal coding style better, not because it would have any inherent advantages over the other.

**Comment by emanuelpalm** [comment]
Actually, the second idea could be simplified even further by completely replacing the `Action` class with a functional interface, like so:

```java
@FunctionalInterface
public interface Action {
    void trigger(final Map<String, Object> environment, final Set<Event> events);
}
```

Using it would be as simple as:

```java
var t0 = new Transition(event, guard, (env, events) -> env.put("T", true), 1);
```
